#14.
def foo():
    try:
        print(1)
    finally:
        print(2)
foo()

Ans:
1
2